# https://taskfile.dev

version: "2"

tasks:
  release:
    cmds:
      - mkdir release || true
      - GOARCH=amd64 GOOS=windows go build -o release/archy.exe
      - GOARCH=amd64 GOOS=linux go build -o release/archy-linux
      - GOARCH=amd64 GOOS=darwin go build -o release/archy-darwin
    silent: true