# https://taskfile.dev

version: "2"

tasks:
  build:
    cmds:
      - mkdir release || true
      - go build -o release/archy
      - go build -o release/archy-svc ./cmd/server
    silent: true
  test:
    cmds:
      - go fmt ./...
      - go test -v ./...
  sonar:
    cmds:
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN